kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backend-pvc-sc
  namespace: akademia
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: filestore-backend
  resources:
    requests:
      storage: 1Ti