apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  volumeName: data-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi