apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity: 
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: ps-vol