apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "*/2 * * * *"
 #schedule: "0 2 * * *" every day at 2:00
 #schedule: "0 5 * * 1-5" from Mon to Fri at 5:00
  successfulJobsHistoryLimit: 20
  failedJobsHistoryLimit: 20
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-job
              image: gregorafc/kube-project-backup:1.0
              volumeMounts:
                - mountPath: /app/storage
                  name: backend-data-volume
                - mountPath: /app/archive
                  name: backend-data-volume
          restartPolicy: OnFailure
          volumes:
            - name: backend-data-volume
              persistentVolumeClaim:
                claimName: backend-pvc