apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: akademia
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000