apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: akademia
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: gregorafc/kube-project-backend:2.0
          volumeMounts:
            - mountPath: /app/storage
              name: backend-data-volume
          env:
            - name: BACKEND_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: BACKEND_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: backend-data-volume
          persistentVolumeClaim:
            claimName: backend-pvc-sc
