apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: akademia
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80