apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: akademia
data:
  nginx.conf: |
    upstream container-backend {
    server backend-service.akademia:3000;
    }

    server {
      listen 80;

      location /api {
        proxy_pass http://container-backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_redirect off;
      }
  
      location / {
      root /usr/share/nginx/html;
      index index.html index.htm;
      try_files $uri $uri/ /index.html =404;
      }
  
      include /etc/nginx/extra-conf.d/*.conf;
    }